### ISSUE TITLE
Install issues with 2.1

### ISSUE THREAD

**Issue by apoapostolov** [megastruktur/foundryvtt-simple-name-generator#2]
Trying to install via manifest gives this error:

![image](https://user-images.githubusercontent.com/4083812/84249771-d8e78000-ab13-11ea-9c27-b112d23ff0b4.png)

**Comment by MNBlockhead** [comment]
Receive an error that may not be compatible with current version of Foundry.  I see it in the compendium and open it, then I select an option, e.g., Slovene Male Names, then click "import", it then makes the chat active, but I have no idea where the imported macro is so that I can execute it.
